services:
  watts-mqtt:
    build: .
    container_name: watts-mqtt
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - WAHA_MQTT_BROKER=tcp://your-ha-ip:1883
      - WAHA_MQTT_USER=your-mqtt-username
      - WAHA_MQTT_PASS=your-mqtt-password
      - WAHA_TOKENS_PATH=/data/tokens.json
    volumes:
      - ./data:/data
